name: Docker Image CI/CD

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
#   schedule:
#     - cron: '26 15 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.13.1'

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ vars.REGISTRY_ADDRESS }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/Amadevus/pwsh-script
      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        id: build-and-push
        uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          script: |
            $InformationPreference = 'Continue'
            $imgs = images/build.ps1 -docker_registry_user '${{ vars.REGISTRY_USERNAME }}'
            Write-Host $imgs
            Set-ActionVariable TAGS ($imgs.tag -join " ")
            Set-ActionVariable DIGESTS ($imgs.digest -join " ")

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: |
          IFS=' ' read -ra tags <<< "$TAGS"
          IFS=' ' read -ra digests <<< "$DIGESTS"          
          for i in "${!tags[@]}"; do
              cosign sign "${tags[$i]}@${digests[$i]}"
          done
